include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    empty_catches: ignore
    deprecated_member_use: ignore
    avoid_relative_lib_imports: ignore
  # appflowy
  exclude:
    # - lib/_widgets/appflowy/**

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    use_build_context_synchronously: false
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    use_super_parameters: true
    depend_on_referenced_packages: false
    avoid_function_literals_in_foreach_calls: false
    # appflowy
    # - always_declare_return_types
    # - require_trailing_commas
    # - unnecessary_raw_strings
    # - use_decorated_box
