name: sayari
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # backend
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.6
  firebase_storage: ^12.4.5
  cloud_functions: ^5.5.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  google_sign_in: ^6.1.4
  # local data
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  # files
  file_picker: ^10.1.9
  open_filex: ^4.3.4
  file_saver: ^0.2.12
  extended_image: any
  # state
  provider: ^6.1.5
  # navigation
  go_router: ^14.2.7
  # style & assets
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  icons_plus: ^5.0.0
  responsive_sizer: ^3.1.1
  reorderables: ^0.6.0
  styled_text: ^8.1.0
  just_the_tooltip: ^0.0.12
  scrollable_positioned_list: ^0.3.8
  flutter_keyboard_visibility: ^6.0.0
  confetti: ^0.7.0
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  # notifications
  awesome_notifications: ^0.9.3+1
  bot_toast: ^4.1.3
  toastification: ^3.0.3
  # others
  collection: ^1.17.1
  url_launcher: ^6.1.10
  intl: ^0.19.0
  flutter_cache_manager: ^3.3.1
  requests: ^4.7.0
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.2
  fl_chart: ^0.67.0
  photo_view: ^0.15.0
  pdf: ^3.10.8
  file: any
  just_audio: ^0.9.46
  connectivity_plus: ^6.1.1
  logger: ^2.5.0
  # datepicker --------------
  syncfusion_flutter_core: ^25.2.7
  # appflowy --------------
  device_info_plus: "^11.0.0"
  diff_match_patch: "^0.4.1"
  html: ^0.15.5
  keyboard_height_plugin: "^0.1.5"
  logging: "^1.2.0"
  markdown: "^7.2.1"
  nanoid: "^1.0.0"
  numerus: "^2.1.2"
  scroll_to_index: "^3.0.1"
  string_validator: "^1.0.0"
  universal_html: "^2.2.4"
  universal_platform: ^1.1.0

dependency_overrides:
  http: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  # appflowy --------------
  flutter_localizations:
    sdk: flutter
  intl_utils: "^2.8.2"
  mockito: "^5.4.1"
  network_image_mock: "^2.1.1"
  path_provider: "^2.0.5"
  pubspec_dependency_sorter: "^1.0.5"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/emojis/
    - assets/audio/
    - assets/editor/images/
    - assets/editor/images/image_toolbar/
    - assets/editor/images/selection_menu/
    - assets/editor/images/toolbar/
    - assets/editor/mobile/
    - assets/editor/mobile/toolbar_icons/

flutter_intl:
  enabled: true
  class_name: AppFlowyEditorLocalizations
  main_locale: en
  arb_dir: lib/_widgets/appflowy/lib/l10n
  output_dir: lib/_widgets/appflowy/lib/src/l10n
  use_deferred_loading: false
  localizely:
    project_id: b7199c7d-eca0-4025-894d-230cdcafa9aa

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sayari.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/sayari.png"

flutter_native_splash:
  # color: "#000000"
  color: "#ffffff"
  color_dark: "#1b1d1c"
  image: "assets/images/sayari.png"
  image_web: "assets/images/sayari256.png"
  fullscreen: true
#
# dart run flutter_launcher_icons
# dart run flutter_native_splash:create
# dart run change_app_package_name:main com.sayari.app
