const List<String> sessionViews = ['Day', 'Week', 'Month', 'Year'];

const Map<String, String> sessionsTypes = {
  'Session': '0',
  'Class': '0',
  'Lecture': '0',
  'Meeting': '0',
  'Appointment': '0',
  'Lab': '0',
  'Fieldwork': '0',
  'Test': '0',
  'Exam': '0',
  'Assignment': '0',
  'Tutorial': '0',
  'Note': '0',
  'Workout': '0',
  'Rest': '0',
  'Wellness': '0',
  'Entertainment': '0',
  'Travel': '0',
  'Adventure': '0',
  'Chore': '0',
  'Meal': '0',
  'Hang Out': '0',
};
