// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6HNn7LqCuu4LteN-U8NT1QjxDbKpRIY',
    appId: '1:347700769995:web:baf5244166d970cdb6d74e',
    messagingSenderId: '347700769995',
    projectId: 'getsayari',
    authDomain: 'getsayari.firebaseapp.com',
    databaseURL: 'https://getsayari-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'getsayari.appspot.com',
    measurementId: 'G-2TBDS6CGKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7bkTYVF0ND6V3DoPf6i45EawWqaNgLD8',
    appId: '1:347700769995:android:358aafdc98433bdfb6d74e',
    messagingSenderId: '347700769995',
    projectId: 'getsayari',
    databaseURL: 'https://getsayari-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'getsayari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKPQT3uyJh2OOorcX4RRdQR0Ly-CXWFA',
    appId: '1:347700769995:ios:28c1e86ca628e4cab6d74e',
    messagingSenderId: '347700769995',
    projectId: 'getsayari',
    databaseURL: 'https://getsayari-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'getsayari.appspot.com',
    iosClientId: '347700769995-c3ivld254rdt6sr5dt0ji1agsst6boga.apps.googleusercontent.com',
    iosBundleId: 'com.sayari.app',
  );

}